---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: custom-scheduler-account
  namespace: kube-system
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: custom-scheduler-node-role
rules:
- apiGroups: [""]
  resources: ["nodes","nodes/status"]
  verbs: ["list","get","watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: custom-scheduler-node-role-binding
subjects:
- kind: ServiceAccount
  name: custom-scheduler-account
  namespace: kube-system
roleRef:
  kind: ClusterRole
  name: custom-scheduler-node-role
  apiGroup: ""  
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: custom-scheduler-kube-scheduler-role-binding
subjects:
- kind: ServiceAccount
  name: custom-scheduler-account
  namespace: kube-system
roleRef:
  kind: ClusterRole
  name: system:kube-scheduler
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: custom-scheduler-volume-scheduler-role-binding
subjects:
- kind: ServiceAccount
  name: custom-scheduler-account
  namespace: kube-system
roleRef:
  kind: ClusterRole
  name: system:volume-scheduler
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: custom-local-scheduler
  namespace: kube-system
spec:
  selector:
    matchLabels:
      app: custom-local-scheduler
  replicas: 1  
  template:
    metadata:
      namespace: kube-system
      labels:
        app: custom-local-scheduler
    spec:
      serviceAccount: custom-scheduler-account
      containers:
      - name: custom-local-scheduler
        image: dockereyes/custom-local-scheduler
        ports:
        - containerPort: 5000
